// <auto-generated />
namespace HappyDaysOne.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RolesUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RolesUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201609091310317_RolesUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
